name: argon_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio:
  get_storage:
  syncfusion_flutter_datepicker:
  syncfusion_flutter_charts: ^21.1.38

  connectivity_plus:
  image_picker:
  file_picker:
  cached_network_image:
  intl:
  month_year_picker:
  kiwi:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner:
  kiwi_generator:
  flutter_native_splash:
  flutter_test: 
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
  web: true
  ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/